//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int id_mail { get; set; }
        public string senter { get; set; }
        public string reciever { get; set; }
        public string subject { get; set; }
        public string context { get; set; }
        public System.DateTime sent_date { get; set; }
        public bool is_read { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
